[build]
buildCommand = "pip install -r requirements.txt && python manage.py collectstatic --noinput"

[deploy]
startCommand = "python manage.py migrate --noinput && gunicorn IN16_Study_Manager.wsgi --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
healthcheckPath = "/login/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
